# File stellar.toml per HAIRCARE26

ACCOUNTS=["GDQ6UGSNP4W63B6JSDHLUBMGQIPALJX5X60RM65D7YKSLFX4V"]

[[CURRENCIES]]
code="DETOX"
issuer="GDQ6UGSNP4W63B6JSDHLUBMGQIPALJX5X60RM65D7YKSLFX4V"
display_decimals=2
name="Shampoo Detox Antiforfora"
desc="Trattamento purificante professionale per capelli."
image="https://happymealtech.github.io/hair/Detox.jpeg"

[[CURRENCIES]]
code="NATURAL"
issuer="GDQ6UGSNP4W63B6JSDHLUBMGQIPALJX5X60RM65D7YKSLFX4V"
display_decimals=2
name="Natural Gel & Cera"
desc="Styling naturale a base di estratti botanici."
image="https://happymealtech.github.io/hair/Natural.jpeg"
