#"Aggiornamento 2"
ACCOUNTS="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"

[[CURRENCIES]]

issuer="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"
display_precision=2
name="AURUM Global Token"
desc="Asset digitale indipendente basato sulla rarit√† digitale e il minimalismo tecnologico. Fornitura limitata a 23 milioni."
image="https://happymealtech.github.io/aur/logo-aurum.jpeg"
documentation="https://happymealtech.github.io/aur/WHITEPAPER.md"
